React blog semana.6
undefined-academy/semana-6 pull request #13
Opened 2023-05-09 22:39 UTC by marisolSv22

2023-05-11 20:19 UTC, manuelmannuel approved these changes
Buen trabajo cumple con lo requerido, como comentario personal, seria bueno trabajr un poco mas el diseño, los bordes rojos hacen distraen un poco, seria bueno obtar por un color mas acorde, algo minimalista, saludos.

2023-05-11 20:28 UTC, marisolSv22 commented
> Buen trabajo cumple con lo requerido, como comentario personal, seria bueno trabajr un poco mas el diseño, los bordes rojos hacen distraen un poco, seria bueno obtar por un color mas acorde, algo minimalista, saludos.

2023-05-11 23:14 UTC, manuelmannuel commented
Muy bien ya se nota el cambio en diseño, solo algo mas que me parecio extraño en las fechas "Publicado: En 24 días", se ve extraño creo que quedaria mejor asi, "Publicado: Hace 24 dias".

2023-05-12 14:39 UTC, marisolSv22 commented
@manuelmannuel  eso va más en la funcionalidad que nos enseñaron de dayjs para humanizar fechas

2023-05-12 18:23 UTC, cadifilippo requested changes
Has eliminado 2 archivos de la raíz del proyecto... debes volver a colocarlos

2023-05-13 17:39 UTC, merged