Se migro el proyecto de blog a react
undefined-academy/semana-6 pull request #18
Opened 2023-05-11 21:39 UTC by facu1391

* Migración del ejercicio de Blog a React
* Se mantiene el uso de Sass como dependencia de desarrollo.
* Se ajustan todas las entradas del blog para que todas puedan ser utilizadas como componentes "Card".

2023-05-12 00:01 UTC, MauBedoya requested changes
Es necesario revisar como se hizo la migración del archivo para humanizar las fechas ya que se están regresando como `invalid date`.
Como observación, revisa la forma en la que Guillermo manejo el tema de la tarjeta extendida, parece que no se están aplicando del todo los estilos en esa parte.

2023-05-12 02:28 UTC, lucianogarriga requested changes
Tengo comentarios similares a los de Mau. Te recomiendo revisar la implementación de la función `humanize` porque arroja 'invalid date'.
Y por otro lado, la card/4 no está tomando bien los estilos.

2023-05-13 23:04 UTC, facu1391 commented
Muchas gracias por la corrección realizada anterior mente, los cambios ya fueron realizados! Espero sus comentarios.
saludos.

2023-05-14 15:52 UTC, lucianogarriga approved these changes
Excelente, recomendaciones corregidas. Gran trabajo Facu!

2023-05-14 17:31 UTC, MauBedoya approved these changes
Todo corregido 👌

2023-05-15 02:45 UTC, merged