componente card mostrado como blog
undefined-academy/semana-6 pull request #19
Opened 2023-05-12 03:39 UTC by fjquants

Se modificó el template de instalación de react y se creó componente card para agregar información tipo blog

2023-05-17 13:06 UTC, diirf requested changes
Hola! En general, has aplicado la estructura de componentes correctamente, sin embargo, también debes incluir el archivo humanize.js para las fechas del blog y el diseño responsivo que has venido haciendo desde la semana 4 con tu blog.

2023-05-17 21:39 UTC, fjquants commented
Agregando la función de humanizar las fechas de entradas de los blogs

2023-05-18 09:22 UTC, diirf approved these changes

2023-05-21 07:17 UTC, carlotagadel approved these changes
Buen trabajo!!! ^^

2023-05-23 02:16 UTC, merged