add blog to react
undefined-academy/semana-6 pull request #2
Opened 2023-05-04 17:34 UTC by Alexis033

2023-05-05 22:19 UTC, Pancratzia requested changes
Hola! Veo que dentro de tu carpeta tienes otra carpeta llamada Blog. Debes sacar los archivos de allí, de modo que se muestren dentro de la carpeta Maikcol-2796. Es decir, que el proyecto este directamente allí tal y como se pide en la asignación

2023-05-05 22:23 UTC, Pancratzia commented
Con respecto a tu proyecto, presentas correctamente tu blog, pero falta implementar la función humanize() de la semana 4

2023-05-05 23:04 UTC, Alexis033 commented
> 

Jeje tienes razón, pensé que había borrado ya esa carpeta, ya agregué la función, se me había olvidado, gracias por tus comentarios.

2023-05-05 23:13 UTC, Pancratzia approved these changes
Listo! A mi criterio ya cumples con todo lo solicitado. A propósito de los PR, podrías hacerle una revisión al mío? Ya que por ahora somos pocos 😅

2023-05-05 23:47 UTC, JoseCamilo84 approved these changes

2023-05-05 23:47 UTC, JoseCamilo84 commented on react-blogs/Maikcol-2796/src/components/Cards.jsx
> +                <time dateTime={entry.date}>{humanizeDate(entry.date)}</time>
Hola, ya veo que agregaste la función humanize(), ya que ayer no la había visto... después todo lo veo bien, está bueno tu trabajo, si tienes tiempito revisas el mío, de antemano gracias

2023-05-06 00:01 UTC, Alexis033 commented on react-blogs/Maikcol-2796/src/components/Cards.jsx
> +                <time dateTime={entry.date}>{humanizeDate(entry.date)}</time>
jejej sí, se me había olvidado agregarla, ya revise tu PR hay 2 cositas que cambiar en el modo mobil, pero está genial.

2023-05-06 00:13 UTC, merged