Week 6 Pull Request
undefined-academy/semana-6 pull request #29
Opened 2023-05-21 07:17 UTC by AliannaFormoso

# Week 6 `PR`

2023-05-26 00:19 UTC, pablo-alex commented on react-blogs/alifm-2843/react-blog/src/components/Main.jsx
> +            <BigFirstCard/>
El componente BigFirstCard es casi exactamente el mismo que Card, si la razon por la que decidiste crear este es para aplicar un estilo aparte, hay otras maneras de resolverlo. Una tal vez seria tener un parametro opcional en Card donde puedes pasarle una id en especifica, otra mejor opcion seria usar css para especificar el primer elemento.

2023-05-26 00:23 UTC, pablo-alex commented on react-blogs/alifm-2843/react-blog/src/styles/base.scss
> +  }
```suggestion
  .card:first-of-type {
  grid-column: 1/4;
  }
```
Con esto no necesitarias una id, podrias eliminar el componente BigFirstCard y podrias añadir el contenido de Beach Destinations en tu array de articles

2023-05-26 00:32 UTC, pablo-alex commented on react-blogs/alifm-2843/react-blog/src/components/Main.jsx
> +                    ))}
```suggestion
            {articles.map((article, key) => (
          <Card
            key={key}
            title={article.title}
            content={article.content}
            image={article.image}
            date={article.date}
          />
        ))}
```
Habia un warning en consola relacionado a las keys

2023-05-26 00:37 UTC, pablo-alex requested changes
Hola @AliannaFormoso, si cometi algun error en mis correciones me lo haces saber, por lo demas todo correcto, el diseño del blog me gusto bastante.

2023-05-29 01:52 UTC, lucianogarriga approved these changes
Por lo visto tu PR cumple con lo solicitado para este ejercicio. Como recomendación te diría que la card principal no sea tan grande, y ver los márgenes de las cards en las vistas mobile sobre todo. El resto todo ok, buen diseño!

2023-05-29 21:38 UTC, Andrssnsdc approved these changes
excelente

2023-05-31 18:21 UTC, pablo-alex approved these changes

2023-06-05 20:03 UTC, AliannaFormoso commented on react-blogs/alifm-2843/react-blog/src/components/Main.jsx
> +            <BigFirstCard/>
Bien, es cierto, lo modifico.

2023-06-05 20:05 UTC, AliannaFormoso commented on react-blogs/alifm-2843/react-blog/src/styles/base.scss
> +  }
Perfecto, genial! Muchas gracias.

2023-06-05 20:11 UTC, AliannaFormoso commented
> Por lo visto tu PR cumple con lo solicitado para este ejercicio. Como recomendación te diría que la card principal no sea tan grande, y ver los márgenes de las cards en las vistas mobile sobre todo. El resto todo ok, buen diseño!

Muchas gracias, tomo en cuenta tus sugerencias de mejora en los cambios que le empiezo a realizar al ejercicio.

2023-06-05 20:11 UTC, AliannaFormoso commented
> excelente

Muchas gracias!

2023-06-05 20:14 UTC, AliannaFormoso commented
> Hola @AliannaFormoso, si cometi algun error en mis correciones me lo haces saber, por lo demas todo correcto, el diseño del blog me gusto bastante.

Para nada, muy apropiada tu revision y comentarios para perfeccionar el aprendizaje sobre React. Muchas gracias!

2023-06-05 21:48 UTC, AliannaFormoso commented
# Week 6 `PR` `Review`

- All reviewers' suggestions were applied.
1. Better design, make the first car smaller.
2. Changed code to render first card.
3. Solved warning on Key.

2023-06-05 21:52 UTC, merged