Pasar el blog de Html a React
undefined-academy/semana-6 pull request #3
Opened 2023-05-05 06:35 UTC by JoseCamilo84

### Semana 6 - Pasar el blog de Html a React

- Agregué la librería dayjs para usar la función humanize() que se creó anteriormente.
- Además utilicé Tailwind para mejorar los estilos.
- Creé 5 componentes de React

2023-05-05 22:39 UTC, Pancratzia approved these changes
Hola! Me ha gustado mucho tu blog. Veo que cumple con todo lo asignado y además considero que es un diseño bastante bonito. Sigue así

2023-05-05 23:26 UTC, JoseCamilo84 commented
gracias

2023-05-05 23:54 UTC, Alexis033 requested changes
Hola, super tu trabajo y diseño, sin embargo, ya que le estás poniendo un alto fijo a las imágenes de las cards entonces debes utilizar la propiedad object-fit o aspect-ratio para que no se deformen tus imágenes cuando cambia el tamaño de la pantalla.
![image](https://user-images.githubusercontent.com/110948692/236585801-23158c0c-83d6-442b-a7e6-0eaf3677971d.png)

También, en la vista mobil mira que dependiendo el tamaño de la fecha te corre el nombre del autor sobre la foto
![image](https://user-images.githubusercontent.com/110948692/236586102-f6bd75eb-d791-44f1-ae9a-e7a9e921d66a.png)

Y en la fecha en la etiqueta <time> te falta la propiedad "datetime".

2023-05-06 03:30 UTC, Alexis033 approved these changes

2023-05-06 16:38 UTC, merged